// 오늘의 운세 프리미엄 데이터
// 일간(日干)별 상세 운세 데이터

export interface DailyPremiumData {
  dayElement: string;
  personality: string;
  todayEnergy: string;
  detailAdvice: string[];
  hourlyFortune: {
    period: string;
    score: number;
    activity: string;
    warning: string;
  }[];
  luckyActions: string[];
  avoidActions: string[];
  relationshipTip: string;
  financeTip: string;
  healthTip: string;
  spiritualMessage: string;
}

// 10일간별 오늘의 운세 상세 데이터
export const dailyPremiumByDayStem: Record<string, DailyPremiumData> = {
  '갑': {
    dayElement: '목',
    personality: '창의적이고 진취적인 기운을 타고났습니다. 새로운 시작에 강하고 리더십이 있습니다.',
    todayEnergy: '오늘은 새로운 아이디어가 샘솟는 날입니다. 머릿속에 떠오르는 영감을 놓치지 마세요.',
    detailAdvice: [
      '오전에 중요한 결정을 내리세요. 판단력이 맑습니다.',
      '초록색 계열의 옷이나 소품이 행운을 가져옵니다.',
      '동쪽 방향으로 움직이면 좋은 기운을 받습니다.',
      '나무와 관련된 활동(산책, 원예)이 기운을 보충합니다.',
    ],
    hourlyFortune: [
      { period: '05:00-07:00', score: 85, activity: '명상, 계획 수립', warning: '서두르지 마세요' },
      { period: '07:00-09:00', score: 90, activity: '중요 미팅, 프레젠테이션', warning: '과신은 금물' },
      { period: '09:00-11:00', score: 75, activity: '서류 작업, 계약', warning: '꼼꼼히 확인' },
      { period: '11:00-13:00', score: 70, activity: '가벼운 점심 약속', warning: '과식 주의' },
      { period: '13:00-15:00', score: 65, activity: '휴식, 정보 수집', warning: '졸음 주의' },
      { period: '15:00-17:00', score: 80, activity: '창의적 업무', warning: '집중력 분산 주의' },
      { period: '17:00-19:00', score: 75, activity: '운동, 야외활동', warning: '무리하지 말 것' },
      { period: '19:00-21:00', score: 85, activity: '사교 모임, 데이트', warning: '과음 주의' },
      { period: '21:00-23:00', score: 70, activity: '독서, 자기계발', warning: '수면 시간 확보' },
    ],
    luckyActions: [
      '새로운 프로젝트 시작하기',
      '운동이나 스포츠 활동',
      '창의적인 취미 활동',
      '동료나 친구에게 아이디어 공유',
      '식물에 물 주기',
    ],
    avoidActions: [
      '결단을 미루는 것',
      '논쟁이나 다툼',
      '무리한 투자 결정',
      '과로와 밤샘',
      '부정적인 사람과의 만남',
    ],
    relationshipTip: '오늘은 솔직하게 마음을 표현하기 좋은 날입니다. 갑목의 곧은 기운처럼 진심을 전하면 상대방도 마음을 열 것입니다. 단, 너무 직설적으로 말하면 오해가 생길 수 있으니 부드럽게 표현하세요.',
    financeTip: '새로운 수입원이 생길 조짐이 있습니다. 평소 관심 있던 부업이나 투자처가 있다면 신중하게 검토해보세요. 큰 지출은 다음 주로 미루는 것이 좋습니다.',
    healthTip: '간과 담의 기운이 강한 날입니다. 스트레스를 받으면 바로 발산하고, 신 음식으로 기운을 보충하세요. 스트레칭과 가벼운 산책이 좋습니다.',
    spiritualMessage: '나무가 하늘을 향해 자라듯, 당신도 꿈을 향해 성장하고 있습니다. 오늘 심은 작은 씨앗이 큰 나무가 될 것입니다. 자신을 믿으세요.',
  },
  '을': {
    dayElement: '목',
    personality: '유연하고 적응력이 뛰어납니다. 덩굴처럼 어디에나 어울리며 섬세한 감각을 지녔습니다.',
    todayEnergy: '오늘은 협력과 조화의 기운이 강합니다. 혼자보다 함께할 때 더 큰 성과를 얻습니다.',
    detailAdvice: [
      '팀워크가 필요한 일에 집중하세요.',
      '상대방의 의견을 경청하면 좋은 아이디어를 얻습니다.',
      '연두색이나 하늘색 계열이 행운의 색입니다.',
      '유연한 자세로 상황에 적응하세요.',
    ],
    hourlyFortune: [
      { period: '05:00-07:00', score: 70, activity: '조용한 시간, 명상', warning: '무리한 계획 금지' },
      { period: '07:00-09:00', score: 80, activity: '팀 미팅, 협업', warning: '주도권 내려놓기' },
      { period: '09:00-11:00', score: 85, activity: '고객 응대, 상담', warning: '과도한 양보 주의' },
      { period: '11:00-13:00', score: 75, activity: '점심 네트워킹', warning: '가벼운 음식 선택' },
      { period: '13:00-15:00', score: 70, activity: '자료 정리, 분석', warning: '꼼꼼하게' },
      { period: '15:00-17:00', score: 85, activity: '협상, 계약', warning: '서두르지 말 것' },
      { period: '17:00-19:00', score: 80, activity: '요가, 필라테스', warning: '무리한 동작 금지' },
      { period: '19:00-21:00', score: 90, activity: '친구 만남, 모임', warning: '늦은 시간까지 주의' },
      { period: '21:00-23:00', score: 75, activity: '취미 활동', warning: '충분한 휴식' },
    ],
    luckyActions: [
      '협력 프로젝트 참여',
      '네트워킹 활동',
      '상대방을 도와주기',
      '유연하게 일정 조정하기',
      '화초 돌보기',
    ],
    avoidActions: [
      '혼자 모든 것을 해결하려 하기',
      '고집 부리기',
      '급한 결정',
      '타인 비판하기',
      '갈등 상황 피하지 않기',
    ],
    relationshipTip: '오늘은 상대방에게 맞춰주는 것이 좋은 결과를 가져옵니다. 을목의 유연함처럼 부드럽게 다가가면 관계가 한층 깊어집니다. 작은 선물이나 배려가 큰 감동을 줍니다.',
    financeTip: '여러 사람과 함께하는 투자나 공동 사업에 좋은 기운이 있습니다. 혼자 결정하기보다 전문가나 주변의 조언을 구하세요. 충동 구매는 삼가세요.',
    healthTip: '오늘은 긴장을 풀고 스트레칭을 자주 하세요. 특히 목과 어깨 부위를 풀어주면 좋습니다. 허브차나 녹차가 기분을 안정시켜 줍니다.',
    spiritualMessage: '덩굴이 어디에나 뿌리내리듯, 당신은 어떤 환경에서도 성장할 수 있는 힘을 가지고 있습니다. 유연함은 당신의 가장 큰 무기입니다.',
  },
  '병': {
    dayElement: '화',
    personality: '열정적이고 카리스마가 넘칩니다. 태양처럼 밝고 주변을 밝히는 에너지를 가졌습니다.',
    todayEnergy: '오늘은 에너지가 넘치는 날입니다. 열정을 발산하되 과열되지 않도록 조절하세요.',
    detailAdvice: [
      '오전에 중요한 일을 처리하세요. 에너지가 가장 높습니다.',
      '빨간색이나 주황색이 행운을 가져옵니다.',
      '남쪽 방향이 길합니다.',
      '자신감 있게 행동하되 겸손함을 잃지 마세요.',
    ],
    hourlyFortune: [
      { period: '05:00-07:00', score: 80, activity: '아침 운동', warning: '준비운동 필수' },
      { period: '07:00-09:00', score: 95, activity: '프레젠테이션, 발표', warning: '과도한 자신감 주의' },
      { period: '09:00-11:00', score: 90, activity: '중요 미팅, 협상', warning: '상대 의견 경청' },
      { period: '11:00-13:00', score: 75, activity: '점심 미팅', warning: '매운 음식 주의' },
      { period: '13:00-15:00', score: 65, activity: '휴식, 재충전', warning: '열 내리기' },
      { period: '15:00-17:00', score: 80, activity: '창의적 업무', warning: '집중력 유지' },
      { period: '17:00-19:00', score: 85, activity: '사교 활동', warning: '과음 주의' },
      { period: '19:00-21:00', score: 80, activity: '취미, 문화생활', warning: '무리하지 말 것' },
      { period: '21:00-23:00', score: 70, activity: '휴식, 명상', warning: '수면 시간 확보' },
    ],
    luckyActions: [
      '리더십 발휘하기',
      '새로운 도전 시작하기',
      '사람들 앞에서 발표하기',
      '밝은 에너지 나누기',
      '운동으로 에너지 발산하기',
    ],
    avoidActions: [
      '혼자 있는 시간이 길어지는 것',
      '과도한 경쟁심',
      '화내거나 짜증내기',
      '무리한 일정',
      '과식과 과음',
    ],
    relationshipTip: '오늘은 당신의 따뜻한 에너지가 상대방을 감동시킵니다. 적극적으로 마음을 표현하세요. 다만 너무 뜨겁게 다가가면 상대방이 부담스러워할 수 있으니 적절한 거리감을 유지하세요.',
    financeTip: '사업이나 투자에 좋은 기운이 있습니다. 특히 밝고 활기찬 분야(엔터테인먼트, 스포츠, 교육)와 관련된 곳에서 좋은 소식이 있을 수 있습니다.',
    healthTip: '심장과 소장의 기운이 강한 날입니다. 물을 충분히 마시고 과열되지 않도록 주의하세요. 오후에는 가벼운 휴식을 취하는 것이 좋습니다.',
    spiritualMessage: '태양처럼 빛나는 당신, 오늘도 주변을 밝혀주세요. 당신의 열정은 다른 사람들에게 큰 영감을 줍니다. 빛나되, 타오르지 않도록 균형을 잡으세요.',
  },
  '정': {
    dayElement: '화',
    personality: '따뜻하고 섬세한 촛불 같은 에너지입니다. 조용히 빛나며 주변을 따뜻하게 합니다.',
    todayEnergy: '오늘은 섬세함과 감성이 빛나는 날입니다. 작은 것에서 큰 기쁨을 찾을 수 있습니다.',
    detailAdvice: [
      '세밀한 작업에 집중하세요.',
      '분홍색이나 따뜻한 색조가 행운입니다.',
      '조용한 환경에서 일하면 효율이 높아집니다.',
      '감성적인 접근이 효과적입니다.',
    ],
    hourlyFortune: [
      { period: '05:00-07:00', score: 75, activity: '명상, 일기 쓰기', warning: '급하게 움직이지 말 것' },
      { period: '07:00-09:00', score: 80, activity: '세밀한 업무', warning: '눈 피로 주의' },
      { period: '09:00-11:00', score: 85, activity: '상담, 조언', warning: '감정 이입 과다 주의' },
      { period: '11:00-13:00', score: 80, activity: '소규모 미팅', warning: '가벼운 식사' },
      { period: '13:00-15:00', score: 70, activity: '휴식, 산책', warning: '낮잠 적당히' },
      { period: '15:00-17:00', score: 85, activity: '창작 활동', warning: '완벽주의 주의' },
      { period: '17:00-19:00', score: 80, activity: '문화 활동', warning: '무리하지 않기' },
      { period: '19:00-21:00', score: 90, activity: '가족/연인과 시간', warning: '감정 표현하기' },
      { period: '21:00-23:00', score: 75, activity: '휴식, 차 마시기', warning: '숙면 준비' },
    ],
    luckyActions: [
      '섬세한 작업하기',
      '예술 활동',
      '상대방 경청하기',
      '따뜻한 차 마시기',
      '일기나 글쓰기',
    ],
    avoidActions: [
      '거친 환경에 노출',
      '큰 소리나 소음',
      '급한 결정',
      '과도한 자기희생',
      '완벽주의에 빠지기',
    ],
    relationshipTip: '오늘은 따뜻한 말 한마디가 관계를 깊게 만듭니다. 정화의 부드러운 불꽃처럼 은은하게 마음을 전하세요. 손편지나 작은 선물이 큰 감동을 줄 수 있습니다.',
    financeTip: '큰 투자보다 작은 저축이 좋은 날입니다. 꼼꼼하게 지출을 점검하고, 불필요한 구독 서비스 등을 정리하면 의외의 절약이 가능합니다.',
    healthTip: '눈과 심장을 보호하세요. 전자기기 사용을 줄이고, 따뜻한 차로 몸을 데워주세요. 감정적으로 예민해질 수 있으니 명상이 도움이 됩니다.',
    spiritualMessage: '촛불처럼 조용히 빛나는 당신, 당신의 따뜻함은 어둠 속에서 더욱 빛납니다. 작지만 꾸준한 불꽃이 세상을 밝힙니다.',
  },
  '무': {
    dayElement: '토',
    personality: '산처럼 듬직하고 안정적입니다. 중심을 잡아주는 든든한 존재입니다.',
    todayEnergy: '오늘은 안정과 균형의 에너지가 강합니다. 중심을 잡고 흔들리지 마세요.',
    detailAdvice: [
      '서두르지 말고 차분하게 진행하세요.',
      '노란색, 갈색 계열이 행운입니다.',
      '중앙이나 중심 위치가 길합니다.',
      '신뢰를 주는 행동을 하세요.',
    ],
    hourlyFortune: [
      { period: '05:00-07:00', score: 80, activity: '명상, 계획 정리', warning: '느긋하게' },
      { period: '07:00-09:00', score: 85, activity: '중요 결정', warning: '과욕 금지' },
      { period: '09:00-11:00', score: 80, activity: '실무 업무', warning: '고집 부리지 않기' },
      { period: '11:00-13:00', score: 75, activity: '점심 휴식', warning: '과식 주의' },
      { period: '13:00-15:00', score: 85, activity: '부동산/계약 관련', warning: '서류 꼼꼼히' },
      { period: '15:00-17:00', score: 80, activity: '안정적인 업무', warning: '변화에 유연하게' },
      { period: '17:00-19:00', score: 75, activity: '집안일, 정리', warning: '무리하지 말 것' },
      { period: '19:00-21:00', score: 85, activity: '가족과 시간', warning: '소통하기' },
      { period: '21:00-23:00', score: 80, activity: '휴식, 독서', warning: '일찍 잠자리' },
    ],
    luckyActions: [
      '안정적인 계획 세우기',
      '부동산 관련 활동',
      '저축 시작하기',
      '주변 정리정돈',
      '신뢰 쌓는 행동',
    ],
    avoidActions: [
      '무리한 변화 시도',
      '급한 결정',
      '고집 부리기',
      '과식',
      '감정적 대응',
    ],
    relationshipTip: '오늘은 든든한 지지자가 되어주세요. 무토의 산 같은 안정감으로 상대방에게 신뢰를 주면 관계가 더욱 깊어집니다. 말보다 행동으로 보여주세요.',
    financeTip: '부동산이나 안정적인 자산에 관심을 가지기 좋은 날입니다. 투기보다 투자, 단타보다 장기의 마인드가 좋은 결과를 가져옵니다.',
    healthTip: '위장과 비장이 예민해질 수 있습니다. 규칙적인 식사와 소화에 좋은 음식을 섭취하세요. 스트레스가 위장에 바로 영향을 주니 마음을 편히 하세요.',
    spiritualMessage: '산처럼 흔들리지 않는 당신, 당신의 안정감은 주변 사람들에게 큰 위안이 됩니다. 오늘도 변함없이 그 자리를 지켜주세요.',
  },
  '기': {
    dayElement: '토',
    personality: '기름진 밭처럼 생산적이고 포용력이 있습니다. 모든 것을 받아들이고 키워냅니다.',
    todayEnergy: '오늘은 수용과 성장의 에너지입니다. 새로운 것을 받아들이고 키워보세요.',
    detailAdvice: [
      '포용력 있게 상황을 받아들이세요.',
      '베이지, 크림색이 행운입니다.',
      '실용적인 접근이 효과적입니다.',
      '다른 사람을 도와주면 복이 옵니다.',
    ],
    hourlyFortune: [
      { period: '05:00-07:00', score: 75, activity: '정원 가꾸기, 운동', warning: '천천히 시작' },
      { period: '07:00-09:00', score: 80, activity: '실무 업무', warning: '완벽주의 내려놓기' },
      { period: '09:00-11:00', score: 85, activity: '팀 업무, 협력', warning: '과도한 책임 지지 않기' },
      { period: '11:00-13:00', score: 80, activity: '점심 네트워킹', warning: '건강한 식사' },
      { period: '13:00-15:00', score: 70, activity: '휴식, 정리', warning: '과로 주의' },
      { period: '15:00-17:00', score: 85, activity: '생산적인 업무', warning: '휴식도 필요' },
      { period: '17:00-19:00', score: 80, activity: '요리, 가사', warning: '과로 금지' },
      { period: '19:00-21:00', score: 85, activity: '가족, 친구와 시간', warning: '소통 중요' },
      { period: '21:00-23:00', score: 75, activity: '취미, 휴식', warning: '충분한 수면' },
    ],
    luckyActions: [
      '타인 도와주기',
      '요리하기',
      '정원/화초 가꾸기',
      '봉사활동',
      '실용적인 선물하기',
    ],
    avoidActions: [
      '이기적인 행동',
      '거절하지 못함',
      '과도한 희생',
      '불건강한 음식',
      '게으름',
    ],
    relationshipTip: '오늘은 상대방을 포용하고 키워주는 마음으로 다가가세요. 기토의 비옥한 땅처럼 상대방의 장점을 발견하고 칭찬하면 관계가 풍요로워집니다.',
    financeTip: '생산적인 활동에서 수익이 발생할 수 있습니다. 부업이나 재능 기부가 의외의 수입으로 이어질 수 있습니다. 지출은 실용적인 것에 집중하세요.',
    healthTip: '소화 기관을 보호하세요. 따뜻하고 소화가 잘 되는 음식을 섭취하고, 규칙적인 생활 리듬을 유지하세요. 걷기 운동이 좋습니다.',
    spiritualMessage: '비옥한 땅처럼 모든 것을 받아들이고 성장시키는 당신, 당신의 포용력은 주변을 풍요롭게 합니다. 오늘도 사랑을 심으세요.',
  },
  '경': {
    dayElement: '금',
    personality: '강철처럼 강하고 원칙적입니다. 정의롭고 결단력이 있습니다.',
    todayEnergy: '오늘은 결단과 실행의 에너지입니다. 망설이지 말고 행동으로 옮기세요.',
    detailAdvice: [
      '빠른 결정이 필요한 일에 집중하세요.',
      '흰색, 금색, 은색이 행운입니다.',
      '서쪽 방향이 길합니다.',
      '원칙을 지키되 유연함도 필요합니다.',
    ],
    hourlyFortune: [
      { period: '05:00-07:00', score: 85, activity: '계획 점검', warning: '완고함 주의' },
      { period: '07:00-09:00', score: 90, activity: '중요 결정', warning: '독단 금지' },
      { period: '09:00-11:00', score: 85, activity: '협상, 계약', warning: '상대 존중' },
      { period: '11:00-13:00', score: 75, activity: '점심 미팅', warning: '날카로운 말 주의' },
      { period: '13:00-15:00', score: 70, activity: '분석 업무', warning: '과도한 비판 주의' },
      { period: '15:00-17:00', score: 85, activity: '실행, 마무리', warning: '무리하지 않기' },
      { period: '17:00-19:00', score: 80, activity: '운동', warning: '부상 주의' },
      { period: '19:00-21:00', score: 75, activity: '휴식, 문화활동', warning: '긴장 풀기' },
      { period: '21:00-23:00', score: 80, activity: '반성, 정리', warning: '충분한 휴식' },
    ],
    luckyActions: [
      '결단력 있게 행동하기',
      '운동이나 무술',
      '정리정돈',
      '불필요한 것 정리',
      '원칙 세우기',
    ],
    avoidActions: [
      '우유부단함',
      '너무 날카롭게 말하기',
      '타협 없는 고집',
      '독단적 결정',
      '과도한 음주',
    ],
    relationshipTip: '오늘은 분명하게 의사를 표현하세요. 경금의 칼처럼 깔끔하게 소통하면 오해가 줄어듭니다. 단, 너무 날카롭게 말하면 상처를 줄 수 있으니 배려를 담아 말하세요.',
    financeTip: '분석적인 판단이 좋은 결과를 가져옵니다. 감정에 휘둘리지 말고 숫자와 데이터로 판단하세요. 과감한 정리(불필요한 지출 삭감)가 필요합니다.',
    healthTip: '폐와 대장의 기운을 보호하세요. 호흡 운동과 깊은 심호흡이 도움이 됩니다. 매운 음식은 적당히, 신선한 공기를 마시세요.',
    spiritualMessage: '강철처럼 단단한 당신, 때로는 유연함도 강함입니다. 칼날을 갈듯 자신을 단련하되, 베려 하지 말고 보호하려 하세요.',
  },
  '신': {
    dayElement: '금',
    personality: '보석처럼 빛나고 섬세합니다. 예리한 판단력과 아름다움을 추구합니다.',
    todayEnergy: '오늘은 세련됨과 정교함의 에너지입니다. 디테일에 집중하세요.',
    detailAdvice: [
      '세밀한 작업에 강점이 있는 날입니다.',
      '은색, 파스텔 톤이 행운입니다.',
      '청결하고 정돈된 환경을 만드세요.',
      '품격 있는 행동이 좋은 인상을 줍니다.',
    ],
    hourlyFortune: [
      { period: '05:00-07:00', score: 80, activity: '그루밍, 준비', warning: '과도한 준비 시간 주의' },
      { period: '07:00-09:00', score: 85, activity: '프레젠테이션', warning: '완벽주의 과다 주의' },
      { period: '09:00-11:00', score: 90, activity: '세밀한 업무', warning: '눈 피로 주의' },
      { period: '11:00-13:00', score: 75, activity: '가벼운 점심', warning: '과식 금지' },
      { period: '13:00-15:00', score: 70, activity: '휴식', warning: '예민함 조절' },
      { period: '15:00-17:00', score: 85, activity: '분석, 기획', warning: '비판적 시각 조절' },
      { period: '17:00-19:00', score: 80, activity: '쇼핑, 미용', warning: '과소비 주의' },
      { period: '19:00-21:00', score: 85, activity: '문화생활, 데이트', warning: '완벽함 내려놓기' },
      { period: '21:00-23:00', score: 75, activity: '스킨케어, 휴식', warning: '충분한 수면' },
    ],
    luckyActions: [
      '미용/패션 관련 활동',
      '세밀한 작업',
      '정리정돈',
      '예술 감상',
      '고급스러운 경험',
    ],
    avoidActions: [
      '지저분한 환경',
      '급하고 거친 행동',
      '과도한 완벽주의',
      '남 비판하기',
      '과소비',
    ],
    relationshipTip: '오늘은 세련된 매력을 발산하세요. 신금의 보석 같은 빛남으로 상대방을 사로잡을 수 있습니다. 작은 센스와 배려가 큰 감동을 줍니다.',
    financeTip: '품질 좋은 것에 투자하세요. 싼 것 여러 개보다 좋은 것 하나가 낫습니다. 재테크도 안정적이고 검증된 상품을 선택하세요.',
    healthTip: '피부와 호흡기를 보호하세요. 건조함에 주의하고 수분 섭취와 보습에 신경 쓰세요. 깨끗한 환경이 건강을 지킵니다.',
    spiritualMessage: '보석처럼 빛나는 당신, 당신의 아름다움은 외면만이 아닙니다. 내면의 빛을 갈고 닦으면 더욱 빛나게 됩니다.',
  },
  '임': {
    dayElement: '수',
    personality: '바다처럼 넓고 깊습니다. 지혜롭고 포용력이 있으며 적응력이 뛰어납니다.',
    todayEnergy: '오늘은 지혜와 통찰의 에너지입니다. 깊이 생각하고 흐름을 읽으세요.',
    detailAdvice: [
      '직관을 믿으세요.',
      '검정색, 진한 파란색이 행운입니다.',
      '북쪽 방향이 길합니다.',
      '물과 관련된 활동이 좋습니다.',
    ],
    hourlyFortune: [
      { period: '05:00-07:00', score: 85, activity: '명상, 꿈 해석', warning: '현실과 괴리 주의' },
      { period: '07:00-09:00', score: 80, activity: '전략 기획', warning: '실행도 중요' },
      { period: '09:00-11:00', score: 85, activity: '분석, 연구', warning: '행동으로 옮기기' },
      { period: '11:00-13:00', score: 75, activity: '점심 휴식', warning: '과음 주의' },
      { period: '13:00-15:00', score: 80, activity: '정보 수집', warning: '선택과 집중' },
      { period: '15:00-17:00', score: 85, activity: '상담, 조언', warning: '말보다 경청' },
      { period: '17:00-19:00', score: 80, activity: '수영, 사우나', warning: '차가움 주의' },
      { period: '19:00-21:00', score: 90, activity: '깊은 대화', warning: '감정 표현하기' },
      { period: '21:00-23:00', score: 85, activity: '독서, 공부', warning: '수면 시간 확보' },
    ],
    luckyActions: [
      '깊은 사색',
      '물 관련 활동 (수영, 사우나)',
      '정보 수집과 분석',
      '글쓰기',
      '여행 계획',
    ],
    avoidActions: [
      '표면적인 판단',
      '감정 억압',
      '흐름을 거스르기',
      '과도한 음주',
      '의심이 과함',
    ],
    relationshipTip: '오늘은 깊은 대화를 나누세요. 임수의 바다 같은 깊이로 상대방의 이야기에 귀 기울이면 관계가 한층 깊어집니다. 감정을 표현하는 것도 잊지 마세요.',
    financeTip: '흐름을 읽는 눈이 필요한 날입니다. 트렌드를 파악하고 장기적인 관점에서 투자를 결정하세요. 충동적인 결정은 피하세요.',
    healthTip: '신장과 방광의 기운을 보호하세요. 물을 충분히 마시고, 하체를 따뜻하게 유지하세요. 명상이나 수영이 좋습니다.',
    spiritualMessage: '바다처럼 깊고 넓은 당신, 당신의 지혜는 많은 사람들에게 방향을 제시합니다. 흐르는 물처럼 자연스럽게, 그러나 깊이 있게 살아가세요.',
  },
  '계': {
    dayElement: '수',
    personality: '이슬처럼 맑고 순수합니다. 섬세하고 감성적이며 직관력이 뛰어납니다.',
    todayEnergy: '오늘은 감성과 직관의 에너지입니다. 느끼는 대로 움직이되 현실도 챙기세요.',
    detailAdvice: [
      '감성적인 접근이 효과적입니다.',
      '하늘색, 은은한 색조가 행운입니다.',
      '물가나 조용한 장소가 좋습니다.',
      '직관을 믿되 현실도 점검하세요.',
    ],
    hourlyFortune: [
      { period: '05:00-07:00', score: 80, activity: '명상, 일기', warning: '우울감 주의' },
      { period: '07:00-09:00', score: 75, activity: '조용한 업무', warning: '에너지 관리' },
      { period: '09:00-11:00', score: 80, activity: '창작, 기획', warning: '현실 반영' },
      { period: '11:00-13:00', score: 75, activity: '가벼운 식사', warning: '차가운 음식 주의' },
      { period: '13:00-15:00', score: 70, activity: '휴식, 낮잠', warning: '우울감 관리' },
      { period: '15:00-17:00', score: 80, activity: '감성적 업무', warning: '감정 조절' },
      { period: '17:00-19:00', score: 85, activity: '예술 활동', warning: '현실과 균형' },
      { period: '19:00-21:00', score: 90, activity: '음악, 영화', warning: '감정 이입 과다 주의' },
      { period: '21:00-23:00', score: 80, activity: '명상, 휴식', warning: '숙면' },
    ],
    luckyActions: [
      '예술 감상',
      '감성적인 대화',
      '일기 쓰기',
      '자연 속 산책',
      '명상',
    ],
    avoidActions: [
      '감정에 휘둘리기',
      '비현실적인 판단',
      '우울한 생각에 빠지기',
      '차가운 환경',
      '과도한 감정 소모',
    ],
    relationshipTip: '오늘은 마음을 열고 솔직하게 감정을 나누세요. 계수의 이슬 같은 맑음으로 진심을 전하면 상대방도 마음을 열 것입니다. 작은 감동을 주는 것이 좋습니다.',
    financeTip: '감에 의존하기보다 데이터를 확인하세요. 오늘은 재정 관련 큰 결정을 미루는 것이 좋습니다. 작은 행복을 위한 소비는 괜찮습니다.',
    healthTip: '몸을 따뜻하게 유지하세요. 차가운 음식과 환경은 피하고, 따뜻한 차와 반신욕이 좋습니다. 감정 건강도 챙기세요.',
    spiritualMessage: '이슬처럼 맑고 순수한 당신, 세상의 때가 묻어도 본래의 맑음을 잃지 마세요. 작은 물방울이 모여 큰 강이 되듯, 당신의 작은 행동들이 세상을 바꿉니다.',
  },
};

// 십성별 오늘의 특별 메시지
export const tenGodDailyMessages: Record<string, {
  theme: string;
  mainMessage: string;
  actionAdvice: string;
  relationAdvice: string;
  warningMessage: string;
}> = {
  '비견': {
    theme: '경쟁과 동반자',
    mainMessage: '오늘은 같은 목표를 향해 나아가는 동료와 시너지를 낼 수 있는 날입니다. 경쟁보다 협력을 선택하세요.',
    actionAdvice: '팀 프로젝트에 집중하고, 동료와 정보를 공유하세요. 혼자 하려 하지 마세요.',
    relationAdvice: '비슷한 생각을 가진 사람을 만날 수 있습니다. 친구나 동료와의 관계가 깊어집니다.',
    warningMessage: '지나친 경쟁심은 금물. 이기려 하기보다 함께 성장하는 것을 목표로 하세요.',
  },
  '겁재': {
    theme: '도전과 경쟁',
    mainMessage: '오늘은 강력한 라이벌이 등장할 수 있습니다. 그러나 경쟁은 당신을 더 강하게 만듭니다.',
    actionAdvice: '자신만의 강점에 집중하고, 남과 비교하지 마세요. 묵묵히 자신의 길을 가세요.',
    relationAdvice: '파트너와 의견 충돌이 있을 수 있습니다. 양보와 타협의 자세가 필요합니다.',
    warningMessage: '재물 손실에 주의하세요. 친구의 부탁이나 보증은 신중하게 결정하세요.',
  },
  '식신': {
    theme: '즐거움과 표현',
    mainMessage: '오늘은 창의력이 넘치고 표현력이 풍부해지는 날입니다. 당신의 재능을 마음껏 발휘하세요.',
    actionAdvice: '맛있는 음식을 먹고, 좋아하는 취미를 즐기세요. 예술 활동이 특히 좋습니다.',
    relationAdvice: '유쾌한 대화로 관계가 좋아집니다. 유머 감각을 발휘하세요.',
    warningMessage: '과식과 과음에 주의하세요. 즐거움도 적당해야 건강합니다.',
  },
  '상관': {
    theme: '자유와 반항',
    mainMessage: '오늘은 틀을 깨고 싶은 욕구가 강해집니다. 창의적인 돌파구를 찾을 수 있습니다.',
    actionAdvice: '기존 방식에 의문을 제기하고 새로운 시도를 해보세요. 단, 선을 넘지는 마세요.',
    relationAdvice: '윗사람과 마찰이 있을 수 있습니다. 말을 조심하고 필터링하세요.',
    warningMessage: '날카로운 말로 상처를 줄 수 있습니다. 생각하고 말하세요.',
  },
  '편재': {
    theme: '재물과 모험',
    mainMessage: '오늘은 예상치 못한 수입이나 기회가 찾아올 수 있습니다. 기회를 잡을 준비를 하세요.',
    actionAdvice: '적극적으로 기회를 찾고, 새로운 비즈니스 아이디어를 검토하세요.',
    relationAdvice: '사교적인 활동에서 좋은 인연을 만날 수 있습니다. 네트워킹에 참여하세요.',
    warningMessage: '투기성 투자는 피하세요. 큰 수익 뒤에는 큰 위험이 있습니다.',
  },
  '정재': {
    theme: '안정과 축적',
    mainMessage: '오늘은 꾸준함이 빛을 발하는 날입니다. 작은 것들을 모아 큰 성과를 만드세요.',
    actionAdvice: '저축을 시작하거나, 장기 계획을 세우세요. 성실함이 결실을 맺습니다.',
    relationAdvice: '안정적인 관계가 강화됩니다. 파트너와 미래 계획을 논의해보세요.',
    warningMessage: '너무 조심스러워서 기회를 놓치지 않도록 하세요. 적절한 모험도 필요합니다.',
  },
  '편관': {
    theme: '권위와 압박',
    mainMessage: '오늘은 압박감을 느낄 수 있지만, 그것이 당신을 성장시킵니다. 도전을 받아들이세요.',
    actionAdvice: '상사나 권위자의 피드백을 겸허히 받아들이세요. 스스로를 채찍질할 때입니다.',
    relationAdvice: '엄격한 사람과의 만남이 있을 수 있습니다. 예의를 갖추되 소신은 지키세요.',
    warningMessage: '스트레스 관리에 신경 쓰세요. 과도한 압박은 건강을 해칩니다.',
  },
  '정관': {
    theme: '책임과 명예',
    mainMessage: '오늘은 책임감과 명예가 강조되는 날입니다. 맡은 일에 최선을 다하면 인정받습니다.',
    actionAdvice: '규칙을 지키고 정도를 걸으세요. 정직함이 신뢰를 쌓습니다.',
    relationAdvice: '진지한 만남이 있을 수 있습니다. 결혼이나 약속 관련 좋은 소식이 있을 수 있어요.',
    warningMessage: '너무 형식에 얽매이지 마세요. 유연성도 필요합니다.',
  },
  '편인': {
    theme: '영감과 탐구',
    mainMessage: '오늘은 영감이 샘솟는 날입니다. 새로운 분야를 탐구하고 배움을 추구하세요.',
    actionAdvice: '독서, 강연, 온라인 강의 등으로 지식을 쌓으세요. 직관을 믿으세요.',
    relationAdvice: '스승이나 멘토를 만날 수 있는 날입니다. 가르침을 겸허히 받으세요.',
    warningMessage: '생각에만 빠지지 말고 실천하세요. 이론과 현실의 균형이 필요합니다.',
  },
  '정인': {
    theme: '보살핌과 학습',
    mainMessage: '오늘은 따뜻한 보살핌과 진정한 배움이 있는 날입니다. 감사하는 마음을 가지세요.',
    actionAdvice: '부모님이나 스승께 안부를 전하세요. 감사 편지를 쓰는 것도 좋습니다.',
    relationAdvice: '어른이나 멘토의 조언이 큰 도움이 됩니다. 겸손하게 받아들이세요.',
    warningMessage: '의존적이 되지 않도록 주의하세요. 스스로 성장해야 합니다.',
  },
};
